encoding: utf-8

# SEO相关信息
title: Maxel's Blog
description: A simple student's simple blog.
keywords: Maxel,Black,Blog,Java,HTML,Minecraft,Pd2,MXCode
author: Maxel Black
footerText: 'Copyright © 2020 Maxel Black'

# Jekyll基本配置
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'dist.tar.gz']
excerpt_separator: <!--MORE-->

# 域名配置
domainUrl: 'https://maxelbk.pd2.ink'
baseurl: ''

# 吐个槽地址
tucaoUrl: '' 

# 网页菜单
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
      #  - title: 留言
      #    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 社会主义核心价值观
extClickEffect: true

# Google Adsense
# _includes/ext-adsense.html
extAdsense: false

# 腾讯MTA移动分析
# _includes/ext-adsense.html
extMTA: false

# 百度收录自动推送
extBaidu: true

# 数学公式支持
extMath: true

# 友情链接
links:
  - title: Pd2 Forum
    url: https://forum.pd2.ink
  - title: Lapis Apple's Recycle Bin
    url: https://laple.top
  - title: JackieCat的小站
    url: https://www.jackiecat.xyz
  - title: 林槐的杂货铺 \# 要来点什么吗 QWQ
    url: https://stapx.chuhelan.com
